# https://medium.com/@zbbergma/dockerizing-a-node-js-postgresql-app-backend-ac81750cf6df
# https://docs.docker.com/compose/environment-variables/#the-env-file
version: '3'
services:
  api:
    build: .
    depends_on:
      - db
    environment:
    - DATABASE_URL=postgres://postgres:password@db:5432/stack
    - MAIL_FROM
    - MAIL_TO
    - SMTP_URL
    ports:
    - 3000:3000
    - 4000:4000
    volumes:
    - .:/code
    - /code/node_modules
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: stack
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
    - 5432:5432
    volumes:
    - ./packages/db/initdb.d:/docker-entrypoint-initdb.d
